# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-09 02:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endereco_ip', models.CharField(max_length=15, unique=True)),
                ('eh_fonte', models.BooleanField()),
                ('numero_pacotes', models.IntegerField()),
                ('pais', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='IpTables',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_pacotes', models.IntegerField()),
            ],
        ),
    ]
