# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-09 23:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ip',
            name='endereco_ip',
            field=models.CharField(max_length=15),
        ),
    ]
