# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-11 18:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20171210_1856'),
    ]

    operations = [
        migrations.CreateModel(
            name='IpsFonte',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endereco_ip', models.CharField(max_length=15, unique=True)),
                ('numero_pacotes', models.IntegerField()),
                ('pais', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Portas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30, unique=True)),
                ('numero_porta', models.CharField(max_length=15)),
                ('quantidade', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Ip',
        ),
    ]
