# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-11 23:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20171211_1836'),
    ]

    operations = [
        migrations.AddField(
            model_name='ipsfonte',
            name='ident',
            field=models.IntegerField(default=0, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name='portas',
            name='ident',
            field=models.IntegerField(default=0, editable=False, unique=True),
        ),
    ]
