# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-11 23:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20171211_2334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ipsfonte',
            name='ident',
            field=models.IntegerField(default=0, unique=True),
        ),
        migrations.AlterField(
            model_name='portas',
            name='ident',
            field=models.IntegerField(default=0, unique=True),
        ),
    ]
