# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-12 00:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20171211_2335'),
    ]

    operations = [
        migrations.AddField(
            model_name='iptables',
            name='ident',
            field=models.IntegerField(default=0, unique=True),
        ),
    ]
